// constants.js
import fs from "fs";
import config from "config"

export const characters = JSON.parse(fs.readFileSync(config.get("CHARACTER_PATH") + "\\characters.json"));

const {
  model_path,
  index_path,
  char_photo,
  name,
  gender,
} = characters[0]

const pith = gender === "male" ? 0 : gender === "female" ? 12 : 6;

export const INITIAL_SESSION = {
  loadConfig: {},
  isAvalible: true,
  settingPith: false,
  settingMangioCrepeHop: false,
  settingFeatureRatio: false,
  settingProtectVoiceless: false,
  waitingForCover: false,
  settingVocalVolume: false,
  waitForPredlog: false,
  settingInstrumentVolume: false,
  settingVoiceSpeed: false,
  waitForPresetSave: false,
  waitForSeparate: false,
  waitForVoice: false,
  waitForModelName: false,
  waitForModelDesc: false,
  waitForModelGender: false,
  waitForMinPich: false,
  waitForMaxPich: false,
  waitForEchoDelay: false,
  waitForEchoPower: false,
  waitForReverb: false,
  waitForAutotuneAttack: false,
  waitForAutotuneStr: false,
  phoneEffect : false,
  echoDelay: 0.3,
  echoPower: 0.1,
  reverbPower: 0.0005,
  autotune_attack: 0.1,
  autotune_strength: 0.9,
  reverbOn: false,
  echoOn: false,
  autoTune: false,
  neuroAutoTune: false,
  minPich: 50,
  maxPich: 1100,
  voiceModelName: "",
  voiceModelDesc: "",
  voiceModelGender: "",
  voiceOrAudioOut : "audio",
  mergeAudio: false,
  testVoice: false,
  firstFile: null,
  secondFile: null,
  previousMessageId: null,
  voiceActor: "aidar",
  audioProcessPower : "nothing",
  pith,
  method: "rmvpe",
  mangio_crepe_hop: 128,
  feature_ratio: 0.8,
  protect_voiceless: 0.33,
  voice_volume: 1.4,
  instrumnet_volume: 0.6,
  voice_speed: 0.95,
  model_path,
  index_path,
  char_photo,
  audioSample: "",
  name,
  gender,
  voice_preset: "male",
};
